// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/DenisKhanov/shorterURL/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetOriginalURL mocks base method.
func (m *MockRepository) GetOriginalURL(ctx context.Context, shortURL string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOriginalURL", ctx, shortURL)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOriginalURL indicates an expected call of GetOriginalURL.
func (mr *MockRepositoryMockRecorder) GetOriginalURL(ctx, shortURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOriginalURL", reflect.TypeOf((*MockRepository)(nil).GetOriginalURL), ctx, shortURL)
}

// GetShortBatchURL mocks base method.
func (m *MockRepository) GetShortBatchURL(ctx context.Context, batchURLRequests []models.URLRequest) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShortBatchURL", ctx, batchURLRequests)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShortBatchURL indicates an expected call of GetShortBatchURL.
func (mr *MockRepositoryMockRecorder) GetShortBatchURL(ctx, batchURLRequests interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShortBatchURL", reflect.TypeOf((*MockRepository)(nil).GetShortBatchURL), ctx, batchURLRequests)
}

// GetShortURL mocks base method.
func (m *MockRepository) GetShortURL(ctx context.Context, originalURL string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShortURL", ctx, originalURL)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShortURL indicates an expected call of GetShortURL.
func (mr *MockRepositoryMockRecorder) GetShortURL(ctx, originalURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShortURL", reflect.TypeOf((*MockRepository)(nil).GetShortURL), ctx, originalURL)
}

// GetStats mocks base method.
func (m *MockRepository) GetStats(ctx context.Context) (models.Stats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx)
	ret0, _ := ret[0].(models.Stats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockRepositoryMockRecorder) GetStats(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockRepository)(nil).GetStats), ctx)
}

// GetUserURLs mocks base method.
func (m *MockRepository) GetUserURLs(ctx context.Context) ([]models.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserURLs", ctx)
	ret0, _ := ret[0].([]models.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserURLS indicates an expected call of GetUserURLS.
func (mr *MockRepositoryMockRecorder) GetUserURLS(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserURLs", reflect.TypeOf((*MockRepository)(nil).GetUserURLs), ctx)
}

// MarkURLsAsDeleted mocks base method.
func (m *MockRepository) MarkURLsAsDeleted(ctx context.Context, URLSToDel []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkURLsAsDeleted", ctx, URLSToDel)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkURLsAsDeleted indicates an expected call of MarkURLsAsDeleted.
func (mr *MockRepositoryMockRecorder) MarkURLsAsDeleted(ctx, URLSToDel interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkURLsAsDeleted", reflect.TypeOf((*MockRepository)(nil).MarkURLsAsDeleted), ctx, URLSToDel)
}

// Ping mocks base method.
func (m *MockRepository) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockRepositoryMockRecorder) Ping(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockRepository)(nil).Ping), ctx)
}

// StoreBatchURL mocks base method.
func (m *MockRepository) StoreBatchURL(ctx context.Context, batchURLtoStores map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreBatchURL", ctx, batchURLtoStores)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreBatchURL indicates an expected call of StoreBatchURL.
func (mr *MockRepositoryMockRecorder) StoreBatchURL(ctx, batchURLtoStores interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreBatchURL", reflect.TypeOf((*MockRepository)(nil).StoreBatchURL), ctx, batchURLtoStores)
}

// StoreURL mocks base method.
func (m *MockRepository) StoreURL(ctx context.Context, originalURL, shortURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreURL", ctx, originalURL, shortURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreURL indicates an expected call of StoreURL.
func (mr *MockRepositoryMockRecorder) StoreURL(ctx, originalURL, shortURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreURL", reflect.TypeOf((*MockRepository)(nil).StoreURL), ctx, originalURL, shortURL)
}

// MockEncoder is a mock of Encoder interface.
type MockEncoder struct {
	ctrl     *gomock.Controller
	recorder *MockEncoderMockRecorder
}

// MockEncoderMockRecorder is the mock recorder for MockEncoder.
type MockEncoderMockRecorder struct {
	mock *MockEncoder
}

// NewMockEncoder creates a new mock instance.
func NewMockEncoder(ctrl *gomock.Controller) *MockEncoder {
	mock := &MockEncoder{ctrl: ctrl}
	mock.recorder = &MockEncoderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEncoder) EXPECT() *MockEncoderMockRecorder {
	return m.recorder
}

// CryptoBase62Encode mocks base method.
func (m *MockEncoder) CryptoBase62Encode() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CryptoBase62Encode")
	ret0, _ := ret[0].(string)
	return ret0
}

// CryptoBase62Encode indicates an expected call of CryptoBase62Encode.
func (mr *MockEncoderMockRecorder) CryptoBase62Encode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CryptoBase62Encode", reflect.TypeOf((*MockEncoder)(nil).CryptoBase62Encode))
}

// MockURLInMemoryRepository is a mock of URLInMemoryRepository interface.
type MockURLInMemoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockURLInMemoryRepositoryMockRecorder
}

// MockURLInMemoryRepositoryMockRecorder is the mock recorder for MockURLInMemoryRepository.
type MockURLInMemoryRepositoryMockRecorder struct {
	mock *MockURLInMemoryRepository
}

// NewMockURLInMemoryRepository creates a new mock instance.
func NewMockURLInMemoryRepository(ctrl *gomock.Controller) *MockURLInMemoryRepository {
	mock := &MockURLInMemoryRepository{ctrl: ctrl}
	mock.recorder = &MockURLInMemoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLInMemoryRepository) EXPECT() *MockURLInMemoryRepositoryMockRecorder {
	return m.recorder
}

// SaveBatchToFile mocks base method.
func (m *MockURLInMemoryRepository) SaveBatchToFile() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveBatchToFile")
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveBatchToFile indicates an expected call of SaveBatchToFile.
func (mr *MockURLInMemoryRepositoryMockRecorder) SaveBatchToFile() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveBatchToFile", reflect.TypeOf((*MockURLInMemoryRepository)(nil).SaveBatchToFile))
}
